### PR TITLE
fixed the interval error

### PR DESCRIPTION
**Pull request by qk98**

### CODE REVIEW

**Comment by wang-ps** [comment]
Sorry, what do you mean by the interval error?

**Comment by qk98** [comment]
The distance between two adjacent voxels is 2.0 / (m-1), not 2.0 / m for a m^3 volume.

**Comment by wang-ps** [comment]
The original code is correct. Please check the following code.
https://github.com/wang-ps/mesh2sdf/blob/1b54d1f5458d8622c444f78d4477f600a6fe50e1/csrc/makelevelset3.cpp#L131

**Comment by qk98** [comment]
The voxel indexes are clamped to [0, n-1]，so, the max corner (top-right-front) is [(n-1)*dx -1.0, (n-1)*dx - 1.0, (n-1)*dx - 1.0]. if dx=2.0 / n, the max corner is [(n-1)*2.0/n -1.0, (n-1)*2.0/n -1.0, (n-1)*2.0/n -1.0], unmatched with the ground truth [1.0, 1.0, 1.0].
image

**Comment by wang-ps** [comment]
Take n=4 as an example, the code computes the SDFs on the grids marked with x as shown in the following figure.  This setting makes it convenient for using the marching cube algorithm.

Untitled

**Comment by qk98** [comment]
OK, it's a feature, not a bug.

**Pull request closed without merging**
